0. Librairies

In [24]:
# core scientific stack
import pandas as pd
import numpy as np

# visualization
import matplotlib.pyplot as plt
import seaborn as sns

# ML: Data Splitting & Validation
from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    GridSearchCV,
    cross_validate
)



import warnings
warnings.filterwarnings('ignore')

# constant
RSEED = 10

1. Data import

In [15]:
# import data from CSV
data_raw = pd.read_csv('data/kickstarter_projects.csv')

In [16]:
# check import
data_raw.head()

,ID,Name,Category,Subcategory,Country,Launched,Deadline,Goal,Pledged,Backers,State
0,1860890148,Grace Jones Does Not Give A F$#% T-Shirt (limi...,Fashion,Fashion,United States,2009-04-21 21:02:48,2009-05-31,1000,625,30,Failed
1,709707365,CRYSTAL ANTLERS UNTITLED MOVIE,Film & Video,Shorts,United States,2009-04-23 00:07:53,2009-07-20,80000,22,3,Failed
2,1703704063,drawing for dollars,Art,Illustration,United States,2009-04-24 21:52:03,2009-05-03,20,35,3,Successful
3,727286,Offline Wikipedia iPhone app,Technology,Software,United States,2009-04-25 17:36:21,2009-07-14,99,145,25,Successful
4,1622952265,Pantshirts,Fashion,Fashion,United States,2009-04-27 14:10:39,2009-05-26,1900,387,10,Failed

In [17]:
# renaming columns with lower case
data_raw.columns = data_raw.columns.str.lower()
data_raw.head()

,id,name,category,subcategory,country,launched,deadline,goal,pledged,backers,state
0,1860890148,Grace Jones Does Not Give A F$#% T-Shirt (limi...,Fashion,Fashion,United States,2009-04-21 21:02:48,2009-05-31,1000,625,30,Failed
1,709707365,CRYSTAL ANTLERS UNTITLED MOVIE,Film & Video,Shorts,United States,2009-04-23 00:07:53,2009-07-20,80000,22,3,Failed
2,1703704063,drawing for dollars,Art,Illustration,United States,2009-04-24 21:52:03,2009-05-03,20,35,3,Successful
3,727286,Offline Wikipedia iPhone app,Technology,Software,United States,2009-04-25 17:36:21,2009-07-14,99,145,25,Successful
4,1622952265,Pantshirts,Fashion,Fashion,United States,2009-04-27 14:10:39,2009-05-26,1900,387,10,Failed

In [ ]:
# 11 columns: 
# id
# name
# category
# subcategory
# country: Country of product origin
# launched: Date the project was launched
# deadline: Deadline for crowdfunding
# goal: Amount of money the creater needs to complete the project (USD)
# pledged: Amount of money pledged to by the crowd (USD)
# backers: Number of backers
# state: Current condition the project is in (as of 2018-01-02)

In [31]:
# 374 853 rows
# 11 columns
data_raw.shape

(374853, 11)

2. Train/Test Split

In [ ]:
# features
X = data_raw.drop('state', axis=1)
X

,id,name,category,subcategory,country,launched,deadline,goal,pledged,backers
0,1860890148,Grace Jones Does Not Give A F$#% T-Shirt (limi...,Fashion,Fashion,United States,2009-04-21 21:02:48,2009-05-31,1000,625,30
1,709707365,CRYSTAL ANTLERS UNTITLED MOVIE,Film & Video,Shorts,United States,2009-04-23 00:07:53,2009-07-20,80000,22,3
2,1703704063,drawing for dollars,Art,Illustration,United States,2009-04-24 21:52:03,2009-05-03,20,35,3
3,727286,Offline Wikipedia iPhone app,Technology,Software,United States,2009-04-25 17:36:21,2009-07-14,99,145,25
4,1622952265,Pantshirts,Fashion,Fashion,United States,2009-04-27 14:10:39,2009-05-26,1900,387,10
...,...,...,...,...,...,...,...,...,...,...
374848,1486845240,Americas Got Talent - Serious MAK,Music,Hip-Hop,United States,2018-01-02 14:13:09,2018-01-16,500,0,0
374849,974738310,EVO Planner: The World's First Personalized Fl...,Design,Product Design,United States,2018-01-02 14:15:38,2018-02-09,15000,269,8
374850,2106246194,"Help save La Gattara, Arizona's first Cat Cafe!",Food,Food,United States,2018-01-02 14:17:46,2018-01-16,10000,165,3
374851,1830173355,Digital Dagger Coin,Art,Art,United States,2018-01-02 14:38:17,2018-02-01,650,7,1
374852,1339173863,Spirits of the Forest,Games,Tabletop Games,Spain,2018-01-02 15:02:31,2018-01-26,24274,4483,82

In [20]:
# target
y = data_raw['state']
y

0             Failed
1             Failed
2         Successful
3         Successful
4             Failed
             ...
374848          Live
374849          Live
374850          Live
374851          Live
374852          Live
Name: state, Length: 374853, dtype: object

In [ ]:
# to do some data cleaning?
y.unique()

array(['Failed', 'Successful', 'Canceled', 'Suspended', 'Live'],
      dtype=object)

In [27]:
# split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state = RSEED 

)
# stratefy ?
# shuffle ?



# Sanity check
print('X_train shape: ', X_train.shape)
print('y_train shape: ',y_train.shape)
print('X_test shape: ',X_test.shape)
print('y_test shape: ',y_test.shape)

X_train shape:  (262397, 10)
y_train shape:  (262397,)
X_test shape:  (112456, 10)
y_test shape:  (112456,)

3. EDA

3.1 Feature overview and data types

In [28]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 262397 entries, 194727 to 345353
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           262397 non-null  int64
 1   name         262397 non-null  object
 2   category     262397 non-null  object
 3   subcategory  262397 non-null  object
 4   country      262397 non-null  object
 5   launched     262397 non-null  object
 6   deadline     262397 non-null  object
 7   goal         262397 non-null  int64
 8   pledged      262397 non-null  int64
 9   backers      262397 non-null  int64
dtypes: int64(4), object(6)
memory usage: 22.0+ MB

In [29]:
X_train.head()

,id,name,category,subcategory,country,launched,deadline,goal,pledged,backers
194727,1531167725,Children of Cain,Publishing,Fiction,United States,2015-01-21 02:39:57,2015-02-20,5800,70,4
19540,654690522,RESTORATION,Publishing,Fiction,United States,2011-05-01 11:47:33,2011-06-30,10000,0,0
120006,1662670595,"Mr. C.L. Woodson III new gospel movie ""Preach...",Film & Video,Film & Video,United States,2013-11-21 04:28:19,2013-12-21,5000,101,6
140585,1634560640,Fuse Film Festival,Film & Video,Film & Video,United Kingdom,2014-05-02 07:32:18,2014-05-18,842,51,3
212864,1331680908,Couture Cheval (Canceled),Design,Product Design,United States,2015-04-01 03:23:18,2015-05-01,100,10,1

In [ ]:
# descriptive statistics
X_train.describe().T

# probably have missing values:
# goal ?
# pledged ?
# backers ?

,count,mean,std,min,25%,50%,75%,max
id,262397.0,1.075251e+09,6.194328e+08,5971.0,538460374.0,1.076824e+09,1.611267e+09,2.147476e+09
goal,262397.0,4.643964e+04,1.185244e+06,0.0,2000.0,5.500000e+03,1.584000e+04,1.663614e+08
pledged,262397.0,9.017906e+03,9.077896e+04,0.0,32.0,6.250000e+02,4.057000e+03,2.033899e+07
backers,262397.0,1.063860e+02,9.429868e+02,0.0,2.0,1.200000e+01,5.700000e+01,2.193820e+05

In [33]:
X_train.columns

Index(['id', 'name', 'category', 'subcategory', 'country', 'launched',
       'deadline', 'goal', 'pledged', 'backers'],
      dtype='object')

In [32]:
X_train.id.unique()

array([1531167725,  654690522, 1662670595, ...,   68192244, 1901859242,
        551648802])

In [34]:
X_train.name.unique()

array(['Children of Cain', 'RESTORATION',
       'Mr. C.L. Woodson III  new gospel movie "Preacher Man"', ...,
       'Visual artist moving to Rennes for artist residency',
       "Photo Book of Connor McDavid's 1st NHL Season. (Canceled)",
       'The Royal Game Of Ur: Laser Cut/3d Printed Playable Replica.'],
      dtype=object)

In [37]:
X_train.country.unique()

array(['United States', 'United Kingdom', 'Ireland', 'Spain', 'Canada',
       'France', 'Mexico', 'Austria', 'Australia', 'New Zealand', 'Italy',
       'Denmark', 'Germany', 'Netherlands ', 'Sweden', 'Hong Kong',
       'Japan', 'Norway', 'Singapore', 'Belgium', 'Switzerland',
       'Luxembourg'], dtype=object)

In [ ]:
# Feature grouping

# 1. Continous numerical features
# id
# goal
# pledged
# backers

# 2. Binary features

# 3. Categorical (non binary features)
# name
# category
# subcategory
# country

# 4. Discrete numeric features
# launched
# deadline

3.2 Missing values and data quality

In [ ]:
missing_summary = (
    X_train.isna()
    .mean()
    .mul(100)
    .round(1)
    .rename("missing_percentage")
    .sort_values(ascending=False)
)

# 0 null values
missing_summary

id             0.0
name           0.0
category       0.0
subcategory    0.0
country        0.0
launched       0.0
deadline       0.0
goal           0.0
pledged        0.0
backers        0.0
Name: missing_percentage, dtype: float64

3.3 Duplicate records and data integrity checks

In [ ]:
# Check for fully duplicated rows ==> 0
n_duplicates = X_train.duplicated().sum()
n_duplicates

0

3.4 Distribution and outlier inspection